trigger:
- main

pool: joel

steps:
- script: |
    echo JAVA_HOME=%JAVA_HOME%
    java -version
    mvn -version
  displayName: 'Verify Java and Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\jdk-21'   # adjust this
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'compile'